steps:
  - id: "Executando docker-compose"
    name: 'docker/compose'
    args: [ '-f', 'docker-compose.cloudbuild.yml', 'up', '-d' ]

  - id: "Chown in /var/www"
    name: 'docker'
    args: [ 'exec','-u','root','-t','app','chown','-R','www-data:www-data','/var/www' ]

  - id: "Executando composer"
    name: 'docker'
    args: [ 'exec', '-t', 'app', 'composer', 'install' ]

  - id: "Copiando o arquivo .env.example para .env"
    name: 'docker'
    args: [ 'exec', '-t', 'app', 'cp', '.env.example', '.env' ]

  - id: "Rodando artisan key:generate"
    name: 'docker'
    args: [ 'exec', '-t', 'app', 'php', '/var/www/artisan', 'key:generate' ]

  - id: "Executando migrations"
    name: 'docker'
    args: [ 'exec', '-t', 'app', 'php', '/var/www/artisan', 'migrate' ]

  - id: "Executando phpunit"
    name: 'docker'
    args: [ 'exec', '-t', 'app', 'php', '/var/www/vendor/bin/phpunit', '-c', '/var/www/phpunit.xml' ]
